#!/usr/bin/env python3
"""Emit src/blake2s_sigma.forth — the 10×16-byte BLAKE2s sigma schedule
plus the RFC 7693 IV, packed into word-sized stores.  The generated file
defines:

    blake2s-base    ( -- addr )    load-time anchor (reserved via here/allot)
                                   for all BLAKE2s scratch; sigma lives at
                                   +0..159.
    blake2s-init-sigma              one-shot word that populates sigma.
    blake2s-iv-0 .. blake2s-iv-7    the 8 SHA-256 IV constants.

Call blake2s-init-sigma exactly once at program start.
"""
import struct
import sys

SIGMA = [
    [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,15],
    [14,10, 4, 8, 9,15,13, 6, 1,12, 0, 2,11, 7, 5, 3],
    [11, 8,12, 0, 5, 2,15,13,10,14, 3, 6, 7, 1, 9, 4],
    [ 7, 9, 3, 1,13,12,11,14, 2, 6, 5,10, 4, 0,15, 8],
    [ 9, 0, 5, 7, 2, 4,10,15,14, 1,11,12, 6, 8, 3,13],
    [ 2,12, 6,10, 0,11, 8, 3, 4,13, 7, 5,15,14, 1, 9],
    [12, 5, 1,15,14,13, 4,10, 0, 7, 6, 3, 9, 2, 8,11],
    [13,11, 7,14,12, 1, 3, 9, 5, 0,15, 4, 8, 6, 2,10],
    [ 6,15,14, 9,11, 3, 0, 8,12, 2,13, 7, 1, 4,10, 5],
    [10, 2, 8, 4, 7, 6, 1, 5,15,11, 9,14, 3,12,13, 0],
]

IV = [
    0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
    0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
]

RESERVE = 444   # 160 B sigma + h/t/f/v/m/G slots + round + single-shot inputs

out = sys.stdout

out.write("\\ blake2s_sigma.forth — GENERATED by tools/gen_blake2s_sigma.py.\n")
out.write("\\ Do not edit by hand.\n\n")
out.write("\\ Reserve the scratch region at load time and stash its start in a var\n")
out.write("\\ so every caller goes through here/allot — no hardcoded address.\n")
out.write("var blake2s-base-cell\n")
out.write(f"here {RESERVE} allot blake2s-base-cell !\n")
out.write(": blake2s-base blake2s-base-cell @ ;\n\n")

for i, v in enumerate(IV):
    out.write(f": blake2s-iv-{i} {v} ;   \\ 0x{v:08x}\n")

out.write("\n")
out.write("\\ Pack 160 sigma bytes (10 rounds × 16) as 40 u32 words written\n")
out.write("\\ with w!. At runtime this is 40 stores starting at blake2s-base.\n")
out.write(": blake2s-init-sigma\n")

flat = [b for row in SIGMA for b in row]
assert len(flat) == 160
for idx in range(0, 160, 4):
    word = (flat[idx]
            | (flat[idx + 1] << 8)
            | (flat[idx + 2] << 16)
            | (flat[idx + 3] << 24))
    off = idx
    out.write(f"  {word} blake2s-base {off} + w!\n")
out.write(";\n")
