#!/usr/bin/env python3
"""Generate tabernacle_config.inc from a binary file.

Usage: gen_bin_config.py <binary> [output]
  Default output: src/tabernacle_config.inc

Computes Gimli-Hash (rate=16, capacity=32, output=32) matching
the tabernacle's verification algorithm.
"""
import struct
import sys

def rotl32(x, n):
    return ((x << n) | (x >> (32 - n))) & 0xFFFFFFFF

def gimli_permute(state):
    for r in range(24, 0, -1):
        for col in range(4):
            x = rotl32(state[col], 24)
            y = rotl32(state[col + 4], 9)
            z = state[col + 8]
            state[col] = (z ^ y ^ ((x & y) << 3)) & 0xFFFFFFFF
            state[col + 4] = (y ^ x ^ ((x | z) << 1)) & 0xFFFFFFFF
            state[col + 8] = (x ^ (z << 1) ^ ((y & z) << 2)) & 0xFFFFFFFF
        if r % 4 == 0:
            state[0], state[1] = state[1], state[0]
            state[2], state[3] = state[3], state[2]
            state[0] ^= (0x9e377900 | r)
        elif r % 4 == 2:
            state[0], state[2] = state[2], state[0]
            state[1], state[3] = state[3], state[1]

def gimli_hash(data):
    state = [0] * 12
    i = 0
    while i + 16 <= len(data):
        for j in range(4):
            state[j] ^= struct.unpack_from('<I', data, i + j * 4)[0]
        gimli_permute(state)
        i += 16
    pad = bytearray(16)
    rem = len(data) - i
    pad[:rem] = data[i:i + rem]
    pad[rem] ^= 0x01
    pad[15] ^= 0x80
    for j in range(4):
        state[j] ^= struct.unpack_from('<I', pad, j * 4)[0]
    gimli_permute(state)
    out = b''
    for j in range(4):
        out += struct.pack('<I', state[j])
    gimli_permute(state)
    for j in range(4):
        out += struct.pack('<I', state[j])
    return out

def main():
    if len(sys.argv) < 2:
        print("Usage: gen_bin_config.py <binary> [output]", file=sys.stderr)
        sys.exit(1)
    binary_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else 'src/tabernacle_config.inc'

    with open(binary_path, 'rb') as f:
        data = f.read()

    h = gimli_hash(data)
    words = struct.unpack('<8I', h)

    with open(output_path, 'w') as f:
        f.write("# bin_config.inc -- auto-generated by gen_bin_config\n")
        f.write("# Hash function: gimli-hash (rate=16, capacity=32, output=32)\n")
        f.write(f".equ\tBIN_SIZE,\t\t{len(data)}\n")
        for i, w in enumerate(words):
            f.write(f".equ\tBIN_HASH{i},\t\t0x{w:08X}\n")
        f.write("\n")

    print(f"{binary_path}: {len(data)} bytes", file=sys.stderr)
    print(f"Hash: {h.hex()}", file=sys.stderr)
    print(f"Written to {output_path}", file=sys.stderr)

if __name__ == '__main__':
    main()
