#!/usr/bin/env python3
"""Generate tests/test_fri_e2e.forth — a Forth program that loads a
prover-emitted FRI proof into memory and runs the Forth verifier
against it.  The generated file is auto-checked-in (or regenerated
from this script before testing) so the test runner can pick it up
via the existing run.sh flow.

Run from repo root:
    python3 -m tools.gen_fri_test

Protocol parameters here MUST match the constants in src/fri.forth:
    fri-n0           = 16
    fri-num-layers   =  2
    fri-num-queries  =  4
    fri-final-size   =  4
    fri-G            = 31
"""

from __future__ import annotations

import struct
import sys
from pathlib import Path

from .stark_ref.field import (
    P, G, bb_mul, bb_pow, bb_root_of_unity, bb_to_bb4, bb4_to_bytes,
)
from .stark_ref.transcript import Transcript
from .stark_ref.fri        import fri_prove, FriProof


# ── Test parameters (must match src/fri.forth) ───────────────────────

TRACE_SIZE  = 4
BLOWUP      = 4
N0          = TRACE_SIZE * BLOWUP        # 16
FINAL_SIZE  = 4
NUM_QUERIES = 4
NUM_LAYERS  = 2
LABEL       = b"FRI-test"


# ── Build a known low-degree FRI proof ───────────────────────────────

def _build_proof() -> FriProof:
    """Evaluate p(X) = 1 + 2X + 3X² + 4X³ on a coset of size N0,
    lift to BB⁴, and run fri_prove."""
    coeffs = [1, 2, 3, 4]
    omega  = bb_root_of_unity(N0)
    x = G
    base_evals = []
    for _ in range(N0):
        y = 0
        for c in reversed(coeffs):
            y = (y * x + c) % P
        base_evals.append(y)
        x = bb_mul(x, omega)
    values = [bb_to_bb4(v) for v in base_evals]
    return fri_prove(values, G, omega, Transcript(LABEL),
                     num_queries=NUM_QUERIES, final_size=FINAL_SIZE)


# ── Wire layout (matching src/fri.forth verifier's parser) ───────────

def _serialize(proof: FriProof) -> bytes:
    out = bytearray()

    # Layer roots.
    for r in proof.layer_roots:
        assert len(r) == 32
        out += r

    # Final polynomial as BB⁴ values.
    for v in proof.final_poly:
        out += bb4_to_bytes(v)

    # Per-query openings: for each query, (leaf32, path) per layer.
    for q_idx in range(NUM_QUERIES):
        opens = proof.query_openings[q_idx]
        assert len(opens) == NUM_LAYERS
        for layer_idx, (leaf, path) in enumerate(opens):
            assert len(leaf) == 32
            out += leaf
            for sib in path:
                assert len(sib) == 32
                out += sib

    return bytes(out)


# ── Forth-source emission ────────────────────────────────────────────

PROLOGUE = """\\ AUTO-GENERATED by tools/gen_fri_test.py — do not edit by hand.
\\ Loads a known-good FRI proof into memory and runs the Forth verifier.
\\
\\ requires: blake2s field merkle transcript fri

: check ( flag msg-addr msg-len -- )
  rot if 2drop else s\" FAIL: \" .str .str cr bye then ;

blake2s-init-sigma

\\ Reserve the proof buffer (size matches the serialized layout below).
var proof-cell  here {SIZE} allot proof-cell !
: proof  proof-cell @ ;
"""

EPILOGUE = """
\\ Verify.
proof fri-verify       s\" FRI proof verifies\"  check

s\" PASS\" .str cr
bye
"""


def _emit_loads(buf: bytes) -> str:
    """Emit a sequence of `value addr w!` Forth lines that populate the
    proof buffer four bytes at a time."""
    assert len(buf) % 4 == 0, "proof byte length must be multiple of 4"
    lines = []
    for off in range(0, len(buf), 4):
        word = struct.unpack_from('<I', buf, off)[0]
        lines.append(f"{word} proof {off} + w!")
    return "\n".join(lines) + "\n"


def main() -> int:
    proof = _build_proof()
    blob  = _serialize(proof)

    repo_root = Path(__file__).resolve().parents[1]
    out_path  = repo_root / "tests" / "test_fri_e2e.forth"

    with out_path.open("w") as f:
        f.write(PROLOGUE.format(SIZE=len(blob)))
        f.write(_emit_loads(blob))
        f.write(EPILOGUE)

    print(f"wrote {out_path} ({len(blob)} proof bytes, "
          f"{len(blob)//4} u32 stores)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
