\ blake2s_sigma.forth — GENERATED by tools/gen_blake2s_sigma.py.
\ Do not edit by hand.

\ Reserve the scratch region at load time and stash its start in a var
\ so every caller goes through here/allot — no hardcoded address.
var blake2s-base-cell
here 444 allot blake2s-base-cell !
: blake2s-base blake2s-base-cell @ ;

: blake2s-iv-0 1779033703 ;   \ 0x6a09e667
: blake2s-iv-1 3144134277 ;   \ 0xbb67ae85
: blake2s-iv-2 1013904242 ;   \ 0x3c6ef372
: blake2s-iv-3 2773480762 ;   \ 0xa54ff53a
: blake2s-iv-4 1359893119 ;   \ 0x510e527f
: blake2s-iv-5 2600822924 ;   \ 0x9b05688c
: blake2s-iv-6 528734635 ;   \ 0x1f83d9ab
: blake2s-iv-7 1541459225 ;   \ 0x5be0cd19

\ Pack 160 sigma bytes (10 rounds × 16) as 40 u32 words written
\ with w!. At runtime this is 40 stores starting at blake2s-base.
: blake2s-init-sigma
  50462976 blake2s-base 0 + w!
  117835012 blake2s-base 4 + w!
  185207048 blake2s-base 8 + w!
  252579084 blake2s-base 12 + w!
  134482446 blake2s-base 16 + w!
  101519113 blake2s-base 20 + w!
  33557505 blake2s-base 24 + w!
  50661131 blake2s-base 28 + w!
  788491 blake2s-base 32 + w!
  219087365 blake2s-base 36 + w!
  100863498 blake2s-base 40 + w!
  67698951 blake2s-base 44 + w!
  16976135 blake2s-base 48 + w!
  235605005 blake2s-base 52 + w!
  168101378 blake2s-base 56 + w!
  135200772 blake2s-base 60 + w!
  117768201 blake2s-base 64 + w!
  252314626 blake2s-base 68 + w!
  202047758 blake2s-base 72 + w!
  218302470 blake2s-base 76 + w!
  168168450 blake2s-base 80 + w!
  50858752 blake2s-base 84 + w!
  84348164 blake2s-base 88 + w!
  151064079 blake2s-base 92 + w!
  251725068 blake2s-base 96 + w!
  168037646 blake2s-base 100 + w!
  50726656 blake2s-base 104 + w!
  185074185 blake2s-base 108 + w!
  235342605 blake2s-base 112 + w!
  151191820 blake2s-base 116 + w!
  68091909 blake2s-base 120 + w!
  167904776 blake2s-base 124 + w!
  151916294 blake2s-base 128 + w!
  134218507 blake2s-base 132 + w!
  118293004 blake2s-base 136 + w!
  84542465 blake2s-base 140 + w!
  67633674 blake2s-base 144 + w!
  83953159 blake2s-base 148 + w!
  235473679 blake2s-base 152 + w!
  855043 blake2s-base 156 + w!
;
